name: CI/CD Pipeline - AWS EKS with Versioned Docker Images

on:
  push:
    branches:
      - main
    paths:
      - "automated-k8s-cicd/app/main.py"
      - "automated-k8s-cicd/Dockerfile"

env:
  AWS_REGION: ap-south-1
  CLUSTER_NAME: my-eks-cluster
  IMAGE_NAME: devangkubde88/webapp

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Read & increment version
      - name: Increment version
        id: versioning
        run: |
          VERSION=$(cat VERSION)
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f2)
          NEW_VERSION="$MAJOR.$((MINOR + 1))"

          echo "$NEW_VERSION" > VERSION
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      # Commit updated VERSION file
      - name: Commit version update
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add VERSION
          git commit -m "Bump version to ${{ steps.versioning.outputs.version }}"
          git push

      # Docker login
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
            -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build \
               -t $IMAGE_NAME:${{ steps.versioning.outputs.version }} \
          automated-k8s-cicd


      # Push Docker image
      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:${{ steps.versioning.outputs.version }}

      # AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: $AWS_REGION

      # kubectl
      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.29.0

      # Helm
      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      # kubeconfig
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $CLUSTER_NAME

      # Deploy using Helm
      - name: Deploy to EKS
        run: |
          helm upgrade --install webapp automated-k8s-cicd/helm/myapp \
            --set image.repository=$IMAGE_NAME \
            --set image.tag=${{ steps.versioning.outputs.version }}
